### ISSUE TITLE
make relative 'Ajax with $resource'

### ISSUE THREAD

**Issue by kosich** [LeviBotelho/LearnAngular#28] opened 2015-01-06 05:42 UTC
In the last chapter, called [Ajax with $resource](http://learn-angular.org/#!/lessons/ajax-with-resource)
imho, since the site can be accessed both with and without  'www.' prefix, the Ajax request url should be changed to a relative one, e.g. `/ResourceLesson/Users/:id`. Otherwise ajax request would fail cz of same-origin-policy violation ( tested on chrome ).

& thanks for the tutors!

**Comment by LeviBotelho** [comment] 2015-01-06 07:35
Thanks for reporting this. Another user brought this issue up last week -- I meant to correct it last weekend but didn't get around to it. I'll close this and keep the other open.

**Comment by LeviBotelho** [comment] 2015-01-06 07:35
Closed as duplicate of https://github.com/LeviBotelho/LearnAngular/issues/27

**Closed by LeviBotelho** 2015-01-06 07:35 UTC
Labels: bug

**Comment by kosich** [comment] 2015-01-06 07:37
aw, sorry, missed that.
